### ISSUE TITLE
broken links to playlists to 2023 course videos in readme file

### ISSUE THREAD

**Issue by dianamarek** [sib-swiss/intermediate-python-training#12]
Hello, 
Maybe you want to hide or comment the section about the playlists as we don't have the videos organised anymore in playlists in SIB YT  but soon again in SIB Training YT. the videos nevertheless still exist if you want to point to the first one of each series.
Cheers
Diana

**Comment by WandrilleD** [comment]
SIBtraining YT playlist  have been changed and the links are now OK.
